### PR TITLE
MutatingWebhookConfiguration in values.yaml

### PR DESCRIPTION
**Pull request by ghost**
related https://github.com/kubemod/kubemod-helm/issues/4#issue-987350913

### CODE REVIEW

**Comment by ghost** [comment]
I am not very good at writing Helm charts.

Chart version should be upped definitely (I don't know how much).

**Comment by vassilvk** [comment]
@desaintmartin, the suggestions by @Kirill-Bugaev make sense to me.
Can you please review his PR and provide feedback?

Regarding the PR, aside from not bumping the Helm version, the changes look good to me.

**Review by desaintmartin — CHANGES_REQUESTED** [review]
Looks good, thanks! Could you bump the minor version of the chart? This is new feature according to semver.

**Comment by ghost** [comment]
@desaintmartin done. Chart version is `0.2.0` now.

**Pull request merged**
