### PR TITLE
feat: :sparkles: template job image

### PR DESCRIPTION
**Pull request by lewis-strong**
Template job image as per #23

### CODE REVIEW

**Comment by vassilvk** [comment]
Hi @lewis-strong, thanks for the PR.
Please fix the failing lint test by bumping the helm version: https://github.com/kubemod/kubemod-helm/actions/runs/6298880559/job/17101839725?pr=24

**Comment by lewis-strong** [comment]
@vassilvk - It's been a while since I've updated a versioned helm chart so forgot about this!!!

Updated and pushed 👍

**Comment by vassilvk** [comment]
> @vassilvk - It's been a while since I've updated a versioned helm chart so forgot about this!!!
> 
> Updated and pushed 👍

Thanks. So this is odd - I see the test pipeline failed due to `--timeout` not being recognized.
I'm not the main maintainer of this repo, but I would suggest that you remove the `helm-extra-args: --timeout 600s` line from `ct.yaml` and try again, let's see if this solves the issue. I wonder if this action is pulling in a new version of helm that removed the `timeout` option - unlikely, but I have no other explanation atm.

cc: @desaintmartin

**Comment by lewis-strong** [comment]
Looks like this hasn't worked for a while from the actions workflow history.

I've taken a look and it seems that this is because `helm lint` which ct runs under the hood doesn't support the --timeout option but `helm install` does.

Therefore i've moved the timeout option to be a direct input on the install command within the action workflow rather than part of the config file.

I've tested this locally and seems to resolve the issue.

**Pull request merged**
